version: '2'

services:
  rippled-server:
    build: ./rippled
    restart: always
    ports:
      - '51235:51235'
    volumes:
      - "./ripple/keystore/:/keystore/" 
      - "./ripple/rippled.conf:/etc/rippled.conf"
    command: "--conf /etc/rippled.conf"
