version: '2'

services:
  rippled-server:
    build: ./rippled
    restart: always
    ports:
      - '51235:51235'
      - '5005:5005'
      - '6006:6006'
    volumes:
      - "./rippled/keystore/:/keystore/"
      - "./rippled/rippled.conf/:/etc/opt/ripple/"
#    command: "--conf /rippled.conf/rippled.cfg"